name: mssql_dart
description: High Performance Microsoft SQL Server Driver for Dart 
version: 1.0.1
homepage: 
repository: https://github.com/insinfo/mssql_dart
publish_to: none
environment:
  sdk: '>=3.6.0 <4.0.0'
    
dependencies:  
  galileo_utf: ^3.0.0
  pointycastle: ^4.0.0
  logging: ^1.3.0
  tuple: ^2.0.2
  meta: ^1.12.0

  tlslite:
    path: ../../
  

dev_dependencies:
  test: ^1.26.3
  hex: ^0.2.0
  postgres: any

