name: mssql_dart
description: High Performance Microsoft SQL Server Driver for Dart 
version: 1.0.1
homepage: 
repository: https://github.com/insinfo/mssql_dart

environment:
  sdk: '>=3.6.0 <4.0.0'
    
dependencies:  
  galileo_utf: ^3.0.0
  pointycastle: ^4.0.0
  tuple: ^2.0.2
  meta: ^1.12.0

dev_dependencies:
  test: any